### ISSUE TITLE
[Bug] [Link Utilities] Search link to PCGamingWiki generates an error

### ISSUE THREAD

**Issue by psychopattt** [HerrKnarz/Playnite-Extensions#122] opened 2024-10-23 23:08 UTC
**Describe the bug**
When I right click on a game and select "Search link to..." and "PCGamingWiki", an error is logged and the search window is empty (no results). The "Add link to..." option also fails to add a link to PCGamingWiki, but does not generate an error.

**To Reproduce**
1. Right click on any game
3. Select "Search link to..."
4. Select "PCGamingWiki"
5. An error is logged

**Expected behavior**
The search should return results without logging an error.

**Versions**
 - Windows version: 10
 - Playnite version: 10.34
 - Extension version: 4.1.1

**Log**
```
23-10 18:44:36.315|ERROR|LinkUtilities#Log:Error loading data from PCGamingWiki|C:\Alex\Entwicklung\dotnet\Playnite-Extensions\Generic\LinkUtilities\Helper\ParseHelper.cs|103
System.NullReferenceException: Object reference not set to an instance of an object.
   at LinkUtilities.Helper.ParseHelper.GetMediaWikiResultsFromHtml(String searchUrl, String searchTerm, String websiteUrl, String linkName, Int32 slashCount) in C:\Alex\Entwicklung\dotnet\Playnite-Extensions\Generic\LinkUtilities\Helper\ParseHelper.cs:line 103
```

**Comment by HerrKnarz** [comment] 2024-10-24 21:08
Unfortunately I can't reproduce the error. I can search for links on PCGamingWiki just fine. Is it only happening with specific games? It's also possible, that PCGamingWiki was having issues, when you tried it. Please check again, if it's working for you now, too.

**Comment by psychopattt** [comment] 2024-10-25 00:20
I noticed this problem over a week ago and I've been having it ever since. I just completely reinstalled Link Utilities and I cleared the config. I then tested over 100 games and the search failed and generated the same error for every single one of them. I'll download the project and see if I can find the issue.

**Comment by HerrKnarz** [comment] 2024-10-25 16:08
That's very strange. Especially since in line 103 in the file ParseHelper.cs a NullReferenceException shouldn't even be possible. The code creates an object there, but doesn't access one...

Could you try to open the following link in your browser?

https://www.pcgamingwiki.com/w/index.php?search=Doom&fulltext=1

That's the page the addon tries to open, when searching for Doom. It should give you results to games with Doom in the name. If it doesn't there seems to be an error on PCGamingWiki itself.

**Comment by psychopattt** [comment] 2024-10-25 21:08
From my browser, I can access PCGamingWiki without any issue. Here's a screenshot of the page I see when I click on the link : [PCGamingWiki Doom Search Result](https://github.com/user-attachments/assets/793e43d5-742e-47ad-97c8-bae702dee58d).

I downloaded the project and found the issue. The search fails because the wrong page is loaded. The plugin tries to find a `div` that has the class `searchresults` with this line :
``` C#
var resultNode = doc.DocumentNode.SelectSingleNode("//div[@class='searchresults']");
```
The loaded page does not contain a `div` that has the class `searchresults`, so `resultNode` is set to `null`. Then, on the next line, a query is run on `resultNode` :
``` C#
if (resultNode.SelectSingleNode("./h2/span[text() = 'Page title matches']") != null)
```
`SelectSingleNode` is called on `resultNode` which is `null`, so there is a `NullReferenceException`. Here's a screenshot of the error in the debugger : [Debugger Error](https://github.com/user-attachments/assets/bc6a1a3e-dc1f-47be-9c71-467e22e573c8). So, the source of the problem seems to be in `ParseHelper.cs` in the function `GetMediaWikiResultsFromHtml` on line 108 :
``` C#
var doc = web.Load(string.Format(searchUrl, searchTerm.UrlEncode()));
```

On my PC, the page that is returned by this line is [this one](https://github.com/user-attachments/files/17527518/page.txt). It looks like some kind of error page and it's very different from the page I get when I use the same search URL in my browser. There seems to be an error with javascript and/or cookies.

**Comment by HerrKnarz** [comment] 2024-10-27 13:21
The HTML parser doesn't support JavaScript, so it doesn't work with websites that require JS to load the search results. According to the page you get when loading the URL via the addon, PCGamingWiki needs JS here. The strange thing is, that it works for me and others just fine without JavaScript. For me PCGamingWiki loads the search results directly.

AFAIK I could try to open the webpage in a web view that supports JS, instead of letting the HTML parser load it directly. I don't know if that will fix it though, because it should run without JS. The problem could be something else entirely on PCGamingWiki's side. Since I don't have the issue, I also couldn't confirm if it's working with the web view, then.

**Comment by psychopattt** [comment] 2024-10-27 13:56
If I'm the only one getting this error, I guess it's not worth adding a whole new system. I can still use the plugin for most websites and add links manually for PCGamingWiki and Epic. Thanks a lot for your help, you can close this issue and #123, if you want.

**Comment by HerrKnarz** [comment] 2024-10-27 21:53
For PCGamingWiki I may have a solution. I don't know anymore why I initially used the HTML search page here when there's also an API I could use. I changed it to use the API now, so JavaScript can't be an issue anymore. I'll close the issues then.

**Closed by HerrKnarz** 2024-10-27 21:53 UTC
Labels: bug

**Comment by psychopattt** [comment] 2024-10-28 23:32
I can confirm it works on my side. Thanks!
