### ISSUE TITLE
[Bug] [Link Utilities] Search link to Epic generates an error

### ISSUE THREAD

**Issue by psychopattt** [HerrKnarz/Playnite-Extensions#123] opened 2024-10-23 23:10 UTC
**Describe the bug**
When I right click on a game and select "Search link to..." and "Epic", an error is logged and the search window is empty (no results).

**To Reproduce**
1. Right click on any game
3. Select "Search link to..."
4. Select "Epic"
5. An error is logged

**Expected behavior**
The search should return results without logging an error.

**Versions**
 - Windows version: 10
 - Playnite version: 10.34
 - Extension version: 4.1.1

**Log**
```
23-10 18:57:32.763|ERROR|LinkUtilities#Log:Error loading data from Epic|C:\Alex\Entwicklung\dotnet\Playnite-Extensions\Generic\LinkUtilities\Helper\ParseHelper.cs|45
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at LinkUtilities.Helper.ParseHelper.GetJsonFromApi[T](String apiUrl, String linkName, Encoding encoding) in C:\Alex\Entwicklung\dotnet\Playnite-Extensions\Generic\LinkUtilities\Helper\ParseHelper.cs:line 45
```

**Comment by HerrKnarz** [comment] 2024-10-24 21:13
I can't reproduce the error here, either. Searching for links works for me as expected. Does it happen for you with all games or only specific ones? It's also possible, that Epic also had an issue, when you tried it, but it would be a bit unlikely for Epic and PCGamingWiki at the same time. Another possibility is Epic blocking access from your region to their API. That would explain the "forbidden" at least.

**Comment by psychopattt** [comment] 2024-10-27 13:52
I tried with more than 100 games over the past week and they all generated the same error. I took a look at the code. The error is generated in `client.DownloadString(apiUrl)` in this line (`ParseHelper.cs` > `GetJsonFromApi` > line 45) :
``` C#
return JsonConvert.DeserializeObject<T>(client.DownloadString(apiUrl));
```
Here is the exact error message from the debugger: [Debugger Error](https://github.com/user-attachments/assets/5beee53f-d32d-4f65-a3a3-515be3ea32a1). If I take the same Api URL (e.g. [this one](https://github.com/user-attachments/files/17534111/Api.Url.txt)) and put it in my browser, I get the expected JSON: [Expected Result](https://github.com/user-attachments/files/17534119/Expected.Result.json). From the plugin, the same URL returns a 403 error.

**Comment by HerrKnarz** [comment] 2024-10-27 21:58
I have no idea what could be causing this. Do you perhaps use a VPN or proxy server in your web browser, that Playnite can't use? I really don't know, what could lead to the different response otherwise, since the API doesn't even need an actual browser like some HTML search pages would.

**Comment by psychopattt** [comment] 2024-10-29 00:40
No, I'm not using a VPN or a proxy server. I don't know why it's returning a 403. I think I'm just going to add links manually from now on. Thanks.

**Comment by HerrKnarz** [comment] 2024-10-29 08:37
OK, I'll close the issue then. Can always reopen, if there are more reports of that in the future. So far it works for everyone else I asked yet.

**Closed by HerrKnarz** 2024-10-29 08:37 UTC
Labels: bug
